build:
  maxIssues: 10

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 10
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6
  LongMethod:
    active: true
    threshold: 50
  LargeClass:
    active: true
    threshold: 300

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  ForbiddenComment:
    active: true
    comments: ['TODO:', 'FIXME:', 'STOPSHIP:']
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    max: 3

naming:
  active: true
  FunctionNaming:
    active: true
  ClassNaming:
    active: true
  VariableNaming:
    active: true

potential-bugs:
  active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  LateinitUsage:
    active: false

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithFlowReturnType:
    active: false

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

