build:
  maxIssues: 10

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 10
    ignoreAnnotated: ['Composable']
  LongMethod:
    active: true
    threshold: 60
    ignoreAnnotated: ['Composable']
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6
    ignoreAnnotated: ['Composable']

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  ForbiddenComment:
    active: true
    comments: ['FIXME:', 'STOPSHIP:']
  UnusedParameter:
    active: true
    ignoreAnnotated: ['Composable']

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']

potential-bugs:
  active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true

performance:
  active: true
  ForEachOnRange:
    active: true

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
